// Firebase project: bloodcare-5a516 (auto-generated by scripts/fetch-firebase-config.sh)
const firebaseConfig = {
  apiKey:            "AIzaSyBMNkoovZcsUWR6lJmOBQS-DNUc1g7ZOG0",
  authDomain:        "bloodcare-5a516.firebaseapp.com",
  projectId:         "bloodcare-5a516",
  storageBucket:     "bloodcare-5a516.firebasestorage.app",
  messagingSenderId: "903309908627",
  appId:             "1:903309908627:web:f2a20203b3d3a03023cb66",
};

firebase.initializeApp(firebaseConfig);
const auth = firebase.auth();
