#!/usr/bin/env bash
# Fetch Firebase Web SDK config for bloodcare-5a516 and update firebase-config.js
# Run from blood-donation/: ./scripts/fetch-firebase-config.sh

set -e
cd "$(dirname "$0")/.."
CONFIG_FILE="src/main/webapp/js/firebase-config.js"

echo "Fetching SDK config for project bloodcare-5a516..."

python3 << 'PYEOF'
import json, subprocess, re, pathlib

result = subprocess.run(
    ["firebase", "apps:sdkconfig", "WEB", "--project", "bloodcare-5a516"],
    capture_output=True, text=True
)
# Extract JSON object from CLI output (skip spinner/status lines)
match = re.search(r'\{[\s\S]*\}', result.stdout)
if not match:
    print("Error: Could not fetch SDK config. Run: firebase login")
    raise SystemExit(1)

cfg = json.loads(match.group())
path = pathlib.Path("src/main/webapp/js/firebase-config.js")
path.write_text(f"""// Firebase project: bloodcare-5a516 (auto-generated by scripts/fetch-firebase-config.sh)
const firebaseConfig = {{
  apiKey:            "{cfg['apiKey']}",
  authDomain:        "{cfg['authDomain']}",
  projectId:         "{cfg['projectId']}",
  storageBucket:     "{cfg['storageBucket']}",
  messagingSenderId: "{cfg['messagingSenderId']}",
  appId:             "{cfg['appId']}",
}};

firebase.initializeApp(firebaseConfig);
const auth = firebase.auth();
""")
print(f"Updated {path}")
PYEOF
